# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 1
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/bradl/Dropbox/Documents/CSE_100/Lab7/Lab7/Lab7.cache/wt [current_project]
set_property parent.project_path C:/Users/bradl/Dropbox/Documents/CSE_100/Lab7/Lab7/Lab7.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.2 [current_project]
set_property ip_output_repo c:/Users/bradl/Dropbox/Documents/CSE_100/Lab7/Lab7/Lab7.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/bradl/Dropbox/Documents/CSE_100/Lab7/Lab7/Lab7.srcs/sources_1/new/LFSR.v
  C:/Users/bradl/Dropbox/Documents/CSE_100/Lab7/Lab7/Lab7.srcs/sources_1/new/QSEC.v
  C:/Users/bradl/Dropbox/Documents/CSE_100/Lab7/Lab7/Lab7.srcs/sources_1/new/Timer.v
  C:/Users/bradl/Dropbox/Documents/CSE_100/Lab7/Lab7/Lab7.srcs/sources_1/new/colorSelector.v
  C:/Users/bradl/Dropbox/Documents/CSE_100/Lab7/Lab7/Lab7.srcs/sources_1/new/coordinateGenerator.v
  C:/Users/bradl/Dropbox/Documents/CSE_100/Lab7/Lab7/Lab7.srcs/sources_1/new/countUD2L.v
  C:/Users/bradl/Dropbox/Documents/CSE_100/Lab7/Lab7/Lab7.srcs/sources_1/new/countUD4L.v
  C:/Users/bradl/Dropbox/Documents/CSE_100/Lab7/Lab7/Lab7.srcs/sources_1/new/fourBitCounter.v
  C:/Users/bradl/Dropbox/Documents/CSE_100/Lab7/Lab7/Lab7.srcs/sources_1/new/frog.v
  C:/Users/bradl/Dropbox/Documents/CSE_100/Lab7/Lab7/Lab7.srcs/sources_1/new/frogCounter.v
  C:/Users/bradl/Dropbox/Documents/CSE_100/Lab7/Lab7/Lab7.srcs/sources_1/new/frogJump.v
  C:/Users/bradl/Dropbox/Documents/CSE_100/Lab7/Lab7/Lab7.srcs/sources_1/new/hex7seg.v
  C:/Users/bradl/Dropbox/Documents/CSE_100/Lab7/Lab7/Lab7.srcs/sources_1/new/lab7_clks.v
  C:/Users/bradl/Dropbox/Documents/CSE_100/Lab7/Lab7/Lab7.srcs/sources_1/new/m8_1.v
  C:/Users/bradl/Dropbox/Documents/CSE_100/Lab7/Lab7/Lab7.srcs/sources_1/new/plantCounter.v
  C:/Users/bradl/Dropbox/Documents/CSE_100/Lab7/Lab7/Lab7.srcs/sources_1/new/plantRandomizer.v
  C:/Users/bradl/Dropbox/Documents/CSE_100/Lab7/Lab7/Lab7.srcs/sources_1/new/plants.v
  C:/Users/bradl/Dropbox/Documents/CSE_100/Lab7/Lab7/Lab7.srcs/sources_1/new/ringCounter.v
  C:/Users/bradl/Dropbox/Documents/CSE_100/Lab7/Lab7/Lab7.srcs/sources_1/new/selector.v
  C:/Users/bradl/Dropbox/Documents/CSE_100/Lab7/Lab7/Lab7.srcs/sources_1/new/stateMachine.v
  C:/Users/bradl/Dropbox/Documents/CSE_100/Lab7/Lab7/Lab7.srcs/sources_1/new/timerCounter.v
  C:/Users/bradl/Dropbox/Documents/CSE_100/Lab7/Lab7/Lab7.srcs/sources_1/new/water.v
  C:/Users/bradl/Dropbox/Documents/CSE_100/Lab7/Lab7/Lab7.srcs/sources_1/new/topLevel.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/bradl/Dropbox/Documents/CSE_100/Lab7/Lab7/Lab7.srcs/constrs_1/imports/Lab7/Basys3_Master.xdc
set_property used_in_implementation false [get_files C:/Users/bradl/Dropbox/Documents/CSE_100/Lab7/Lab7/Lab7.srcs/constrs_1/imports/Lab7/Basys3_Master.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top topLevel -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef topLevel.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file topLevel_utilization_synth.rpt -pb topLevel_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
